// Constants for slider and tooltip functionality
export const SLIDER_SELECTOR = '.k-slider.range';
export const TOOLTIP_CLASS = 'k-slider-tooltip';
// Complete list of movie languages with codes and counts (from TMDB)
export const movieLanguages = [
    { label: "None Selected", code: "" },
    { label: "English (642,213)", code: "en" },
    { label: "French (75,891)", code: "fr" },
    { label: "Spanish; Castilian (68,514)", code: "es" },
    { label: "Japanese (61,688)", code: "ja" },
    { label: "German (59,101)", code: "de" },
    { label: "Portuguese (38,978)", code: "pt" },
    { label: "Chinese (30,472)", code: "zh" },
    { label: "Italian (27,122)", code: "it" },
    { label: "Russian (26,805)", code: "ru" },
    { label: "Korean (14,720)", code: "ko" },
    { label: "Czech (13,091)", code: "cs" },
    { label: "Arabic (10,535)", code: "ar" },
    { label: "Dutch; Flemish (10,107)", code: "nl" },
    { label: "Swedish (9,563)", code: "sv" },
    { label: "Hindi (9,553)", code: "hi" },
    { label: "Turkish (8,823)", code: "tr" },
    { label: "Polish (8,248)", code: "pl" },
    { label: "Tagalog (7,985)", code: "tl" },
    { label: "No Language (7,888)", code: "xx" },
    { label: "Cantonese (6,162)", code: "cn" },
    { label: "Danish (6,096)", code: "da" },
    { label: "Indonesian (6,016)", code: "id" },
    { label: "Greek (5,665)", code: "el" },
    { label: "Tamil (5,352)", code: "ta" },
    { label: "Persian (5,142)", code: "fa" },
    { label: "Malayalam (4,549)", code: "ml" },
    { label: "Hungarian (4,467)", code: "hu" },
    { label: "Thai (3,924)", code: "th" },
    { label: "Bengali (3,860)", code: "bn" },
    { label: "Finnish (3,706)", code: "fi" },
    { label: "Ukrainian (3,635)", code: "uk" },
    { label: "Telugu (3,414)", code: "te" },
    { label: "Norwegian (3,390)", code: "no" },
    { label: "Hebrew (3,003)", code: "he" },
    { label: "Slovak (2,839)", code: "sk" },
    { label: "Romanian (2,551)", code: "ro" },
    { label: "Kannada (1,977)", code: "kn" },
    { label: "Serbo-Croatian (1,865)", code: "sh" },
    { label: "Malay (1,709)", code: "ms" },
    { label: "Serbian (1,709)", code: "sr" },
    { label: "Latvian (1,680)", code: "lv" },
    { label: "Catalan; Valencian (1,541)", code: "ca" },
    { label: "Estonian (1,478)", code: "et" },
    { label: "Marathi (1,462)", code: "mr" },
    { label: "Icelandic (1,418)", code: "is" },
    { label: "Vietnamese (1,383)", code: "vi" },
    { label: "Bulgarian (1,330)", code: "bg" },
    { label: "Croatian (1,308)", code: "hr" },
    { label: "Georgian (1,229)", code: "ka" },
    { label: "Slovenian (1,192)", code: "sl" },
    { label: "Lithuanian (1,153)", code: "lt" },
    { label: "Oriya (1,141)", code: "or" },
    { label: "Mongolian (901)", code: "mn" },
    { label: "Kazakh (892)", code: "kk" },
    { label: "Panjabi; Punjabi (885)", code: "pa" },
    { label: "Azerbaijani (799)", code: "az" },
    { label: "Urdu (722)", code: "ur" },
    { label: "Armenian (661)", code: "hy" },
    { label: "Albanian (660)", code: "sq" },
    { label: "Macedonian (610)", code: "mk" },
    { label: "Afrikaans (499)", code: "af" },
    { label: "Kurdish (464)", code: "ku" },
    { label: "Galician (433)", code: "gl" },
    { label: "Nepali (433)", code: "ne" },
    { label: "Basque (424)", code: "eu" },
    { label: "Burmese (416)", code: "my" },
    { label: "Bosnian (391)", code: "bs" },
    { label: "Bokmål, Norwegian; Norwegian Bokmål (353)", code: "nb" },
    { label: "Gujarati (321)", code: "gu" },
    { label: "Sinhala; Sinhalese (315)", code: "si" },
    { label: "Central Khmer (308)", code: "km" },
    { label: "Uzbek (280)", code: "uz" },
    { label: "Amharic (245)", code: "am" },
    { label: "Assamese (229)", code: "as" },
    { label: "Kirghiz; Kyrgyz (202)", code: "ky" },
    { label: "Javanese (194)", code: "jv" },
    { label: "Irish (160)", code: "ga" },
    { label: "Zulu (141)", code: "zu" },
    { label: "Swahili (134)", code: "sw" },
    { label: "Belarusian (127)", code: "be" },
    { label: "Welsh (120)", code: "cy" },
    { label: "Tibetan (111)", code: "bo" },
    { label: "Yiddish (95)", code: "yi" },
    { label: "Northern Sami (84)", code: "se" },
    { label: "Malagasy (81)", code: "mg" },
    { label: "Haitian; Haitian Creole (77)", code: "ht" },
    { label: "Moldavian; Moldovan (75)", code: "mo" },
    { label: "Abkhazian (73)", code: "ab" },
    { label: "Turkmen (73)", code: "tk" },
    { label: "Wolof (72)", code: "wo" },
    { label: "Luxembourgish; Letzeburgesch (68)", code: "lb" },
    { label: "Quechua (65)", code: "qu" },
    { label: "Tajik (63)", code: "tg" },
    { label: "Yoruba (61)", code: "yo" },
    { label: "Pushto; Pashto (60)", code: "ps" },
    { label: "Gaelic; Scottish Gaelic (57)", code: "gd" },
    { label: "Inuktitut (57)", code: "iu" },
    { label: "Divehi; Dhivehi; Maldivian (57)", code: "dv" },
    { label: "Latin (56)", code: "la" },
    { label: "Lao (55)", code: "lo" },
    { label: "Somali (50)", code: "so" },
    { label: "Dzongkha (45)", code: "dz" },
    { label: "Maltese (41)", code: "mt" },
    { label: "Maori (40)", code: "mi" },
    { label: "Faroese (39)", code: "fo" },
    { label: "Bambara (36)", code: "bm" },
    { label: "Guarani (35)", code: "gn" },
    { label: "Hausa (28)", code: "ha" },
    { label: "Kalaallisut; Greenlandic (27)", code: "kl" },
    { label: "Xhosa (24)", code: "xh" },
    { label: "Kinyarwanda (23)", code: "rw" },
    { label: "Cree (22)", code: "cr" },
    { label: "Norwegian Nynorsk; Nynorsk, Norwegian (22)", code: "nn" },
    { label: "Esperanto (21)", code: "eo" },
    { label: "Akan (21)", code: "ak" },
    { label: "Sotho, Southern (20)", code: "st" },
    { label: "Uighur; Uyghur (19)", code: "ug" },
    { label: "Igbo (18)", code: "ig" },
    { label: "Kashmiri (16)", code: "ks" },
    { label: "Lingala (16)", code: "ln" },
    { label: "Cornish (15)", code: "kw" },
    { label: "Sundanese (15)", code: "su" },
    { label: "Fulah (15)", code: "ff" },
    { label: "Sanskrit (14)", code: "sa" },
    { label: "Samoan (13)", code: "sm" },
    { label: "Tigrinya (13)", code: "ti" },
    { label: "Western Frisian (13)", code: "fy" },
    { label: "Tatar (13)", code: "tt" },
    { label: "Ganda (12)", code: "lg" },
    { label: "Chichewa; Chewa; Nyanja (12)", code: "ny" },
    { label: "Shona (12)", code: "sn" },
    { label: "Romansh (12)", code: "rm" },
    { label: "Aymara (11)", code: "ay" },
    { label: "Sindhi (11)", code: "sd" },
    { label: "Twi (11)", code: "tw" },
    { label: "Bashkir (9)", code: "ba" },
    { label: "Tonga (Tonga Islands) (8)", code: "to" },
    { label: "Marshallese (8)", code: "mh" },
    { label: "Chuvash (8)", code: "cv" },
    { label: "Tswana (8)", code: "tn" },
    { label: "Fijian (7)", code: "fj" },
    { label: "Sango (7)", code: "sg" },
    { label: "Breton (7)", code: "br" },
    { label: "Tahitian (7)", code: "ty" },
    { label: "Sardinian (7)", code: "sc" },
    { label: "Chechen (7)", code: "ce" },
    { label: "Interlingua; International Auxiliary Language Association (6)", code: "ia" },
    { label: "Limburgan; Limburger; Limburgish (6)", code: "li" },
    { label: "Bislama (6)", code: "bi" },
    { label: "Occitan (post 1500) (5)", code: "oc" },
    { label: "Navajo; Navaho (5)", code: "nv" },
    { label: "Oromo (5)", code: "om" },
    { label: "Swati (5)", code: "ss" },
    { label: "Ossetian; Ossetic (4)", code: "os" },
    { label: "Kikuyu; Gikuyu (4)", code: "ki" },
    { label: "Corsican (4)", code: "co" },
    { label: "Ojibwa (4)", code: "oj" },
    { label: "Inupiaq (3)", code: "ik" },
    { label: "Tsonga (3)", code: "ts" },
    { label: "Aragonese (3)", code: "an" },
    { label: "Rundi (3)", code: "rn" },
    { label: "Hiri Motu (3)", code: "ho" },
    { label: "Chamorro (3)", code: "ch" },
    { label: "Manx (3)", code: "gv" },
    { label: "Venda (3)", code: "ve" },
    { label: "Afar (2)", code: "aa" },
    { label: "Ndebele, North; North Ndebele (2)", code: "nd" },
    { label: "Ido (2)", code: "io" },
    { label: "Avaric (2)", code: "av" },
    { label: "Ndonga (2)", code: "ng" },
    { label: "Sichuan Yi; Nuosu (2)", code: "ii" },
    { label: "Zhuang; Chuang (2)", code: "za" },
    { label: "Komi (2)", code: "kv" },
    { label: "Herero (1)", code: "hz" },
    { label: "Ndebele, South; South Ndebele (1)", code: "nr" },
    { label: "Kuanyama; Kwanyama (1)", code: "kj" },
    { label: "Ewe (1)", code: "ee" },
    { label: "Interlingue; Occidental (1)", code: "ie" },
    { label: "Kongo (1)", code: "kg" },
    { label: "Kanuri (1)", code: "kr" },
];
